---
title: 'JSC370 Final: Understanding Gender Bias in Self-Reported Software Compensation Data'
date: '2022-04-21'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE)
```

```{r}
# library setup
library(tidyverse)
library(lme4)
```

```{r, eval=F}
# run this if you do not have the csv (same as data/data.Rmd)
library(reticulate)
```

```{python, python.reticulate=FALSE, eval=F}
# run this if you do not have the csv (same as data/data.Rmd)
import pandas as pd
import requests
pd.DataFrame(requests.get('https://www.levels.fyi/js/salaryData.json').json()).to_csv('salary_data.csv', index=False)
```

```{r, eval=F}
# run this if you do not have the csv (same as data/data.Rmd)
salary <- read.csv('salary_data.csv')
salary_interest <- salary %>% select(timestamp, company, level, title, totalyearlycompensation, location, yearsofexperience, yearsatcompany, basesalary, stockgrantvalue, bonus, gender)

salary_interest <- salary_interest %>% mutate(
  totalyearlycompensation = ifelse(totalyearlycompensation<1000, totalyearlycompensation*1000, totalyearlycompensation), 
  basesalary = ifelse(basesalary<1000, basesalary*1000, basesalary),
  stockgrantvalue = ifelse(stockgrantvalue<1000, stockgrantvalue*1000, stockgrantvalue),
  bonus = ifelse(bonus<1000, bonus*1000, bonus))

salary_interest <- salary_interest %>% filter(totalyearlycompensation>quantile(totalyearlycompensation, 0.05), totalyearlycompensation<quantile(totalyearlycompensation, 0.99), basesalary > quantile(basesalary, 0.05),basesalary < quantile(basesalary, 0.99), yearsatcompany < 60)

salary_interest$company <- str_trim(str_to_title(salary_interest$company))
salary_interest$location <- str_trim(str_to_title(salary_interest$location))
salary_interest$date <- as.Date(strptime(salary_interest$timestamp, format="%m/%d/%Y"))

salary_interest$male = ifelse(salary_interest$gender == "Male", 1, 0)
salary_interest$female = ifelse(salary_interest$gender == "Female", 1, 0)
```

### Introduction

### Methods

refer to data/data.Rmd
give brief summary

### Results
 analysis goes here
### Discussion and Limitations

### Summary and Conclusion


### Reproducibility
This document is fully reproducibile unless the data source has been removed. Refer to the `main.Rmd` file in the repository. Some lines of code are hidden.

### References
